// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: cosyvoice.proto

package protos

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CosyVoice_Inference_FullMethodName         = "/cosyvoice.CosyVoice/Inference"
	CosyVoice_SpeechRecognition_FullMethodName = "/cosyvoice.CosyVoice/SpeechRecognition"
)

// CosyVoiceClient is the client API for CosyVoice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CosyVoiceClient interface {
	Inference(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	SpeechRecognition(ctx context.Context, in *ASRRequest, opts ...grpc.CallOption) (*ASRResponse, error)
}

type cosyVoiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCosyVoiceClient(cc grpc.ClientConnInterface) CosyVoiceClient {
	return &cosyVoiceClient{cc}
}

func (c *cosyVoiceClient) Inference(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CosyVoice_ServiceDesc.Streams[0], CosyVoice_Inference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosyVoice_InferenceClient = grpc.ServerStreamingClient[Response]

func (c *cosyVoiceClient) SpeechRecognition(ctx context.Context, in *ASRRequest, opts ...grpc.CallOption) (*ASRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASRResponse)
	err := c.cc.Invoke(ctx, CosyVoice_SpeechRecognition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CosyVoiceServer is the server API for CosyVoice service.
// All implementations must embed UnimplementedCosyVoiceServer
// for forward compatibility.
type CosyVoiceServer interface {
	Inference(*Request, grpc.ServerStreamingServer[Response]) error
	SpeechRecognition(context.Context, *ASRRequest) (*ASRResponse, error)
	mustEmbedUnimplementedCosyVoiceServer()
}

// UnimplementedCosyVoiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCosyVoiceServer struct{}

func (UnimplementedCosyVoiceServer) Inference(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method Inference not implemented")
}
func (UnimplementedCosyVoiceServer) SpeechRecognition(context.Context, *ASRRequest) (*ASRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpeechRecognition not implemented")
}
func (UnimplementedCosyVoiceServer) mustEmbedUnimplementedCosyVoiceServer() {}
func (UnimplementedCosyVoiceServer) testEmbeddedByValue()                   {}

// UnsafeCosyVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CosyVoiceServer will
// result in compilation errors.
type UnsafeCosyVoiceServer interface {
	mustEmbedUnimplementedCosyVoiceServer()
}

func RegisterCosyVoiceServer(s grpc.ServiceRegistrar, srv CosyVoiceServer) {
	// If the following call pancis, it indicates UnimplementedCosyVoiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CosyVoice_ServiceDesc, srv)
}

func _CosyVoice_Inference_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CosyVoiceServer).Inference(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosyVoice_InferenceServer = grpc.ServerStreamingServer[Response]

func _CosyVoice_SpeechRecognition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosyVoiceServer).SpeechRecognition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosyVoice_SpeechRecognition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosyVoiceServer).SpeechRecognition(ctx, req.(*ASRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CosyVoice_ServiceDesc is the grpc.ServiceDesc for CosyVoice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CosyVoice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosyvoice.CosyVoice",
	HandlerType: (*CosyVoiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpeechRecognition",
			Handler:    _CosyVoice_SpeechRecognition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Inference",
			Handler:       _CosyVoice_Inference_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cosyvoice.proto",
}
