// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: cosyvoice.proto

package protos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestPayload:
	//
	//	*Request_SftRequest
	//	*Request_ZeroShotRequest
	//	*Request_CrossLingualRequest
	//	*Request_InstructRequest
	RequestPayload isRequest_RequestPayload `protobuf_oneof:"RequestPayload" dc:"*Request_SftRequest*Request_ZeroShotRequest*Request_CrossLingualRequest*Request_InstructRequest"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_cosyvoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestPayload() isRequest_RequestPayload {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *Request) GetSftRequest() *SftRequest {
	if x != nil {
		if x, ok := x.RequestPayload.(*Request_SftRequest); ok {
			return x.SftRequest
		}
	}
	return nil
}

func (x *Request) GetZeroShotRequest() *ZeroshotRequest {
	if x != nil {
		if x, ok := x.RequestPayload.(*Request_ZeroShotRequest); ok {
			return x.ZeroShotRequest
		}
	}
	return nil
}

func (x *Request) GetCrossLingualRequest() *CrosslingualRequest {
	if x != nil {
		if x, ok := x.RequestPayload.(*Request_CrossLingualRequest); ok {
			return x.CrossLingualRequest
		}
	}
	return nil
}

func (x *Request) GetInstructRequest() *InstructRequest {
	if x != nil {
		if x, ok := x.RequestPayload.(*Request_InstructRequest); ok {
			return x.InstructRequest
		}
	}
	return nil
}

type isRequest_RequestPayload interface {
	isRequest_RequestPayload()
}

type Request_SftRequest struct {
	SftRequest *SftRequest `protobuf:"bytes,1,opt,name=sft_request,json=sftRequest,proto3,oneof"`
}

type Request_ZeroShotRequest struct {
	ZeroShotRequest *ZeroshotRequest `protobuf:"bytes,2,opt,name=zero_shot_request,json=zeroShotRequest,proto3,oneof"`
}

type Request_CrossLingualRequest struct {
	CrossLingualRequest *CrosslingualRequest `protobuf:"bytes,3,opt,name=cross_lingual_request,json=crossLingualRequest,proto3,oneof"`
}

type Request_InstructRequest struct {
	InstructRequest *InstructRequest `protobuf:"bytes,4,opt,name=instruct_request,json=instructRequest,proto3,oneof"`
}

func (*Request_SftRequest) isRequest_RequestPayload() {}

func (*Request_ZeroShotRequest) isRequest_RequestPayload() {}

func (*Request_CrossLingualRequest) isRequest_RequestPayload() {}

func (*Request_InstructRequest) isRequest_RequestPayload() {}

type SftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpkId         string                 `protobuf:"bytes,1,opt,name=spk_id,json=spkId,proto3" json:"spk_id,omitempty"`
	TtsText       string                 `protobuf:"bytes,2,opt,name=tts_text,json=ttsText,proto3" json:"tts_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SftRequest) Reset() {
	*x = SftRequest{}
	mi := &file_cosyvoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SftRequest) ProtoMessage() {}

func (x *SftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SftRequest.ProtoReflect.Descriptor instead.
func (*SftRequest) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{1}
}

func (x *SftRequest) GetSpkId() string {
	if x != nil {
		return x.SpkId
	}
	return ""
}

func (x *SftRequest) GetTtsText() string {
	if x != nil {
		return x.TtsText
	}
	return ""
}

type ZeroshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtsText       string                 `protobuf:"bytes,1,opt,name=tts_text,json=ttsText,proto3" json:"tts_text,omitempty"`
	PromptText    string                 `protobuf:"bytes,2,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	PromptAudio   []byte                 `protobuf:"bytes,3,opt,name=prompt_audio,json=promptAudio,proto3" json:"prompt_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroshotRequest) Reset() {
	*x = ZeroshotRequest{}
	mi := &file_cosyvoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroshotRequest) ProtoMessage() {}

func (x *ZeroshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroshotRequest.ProtoReflect.Descriptor instead.
func (*ZeroshotRequest) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{2}
}

func (x *ZeroshotRequest) GetTtsText() string {
	if x != nil {
		return x.TtsText
	}
	return ""
}

func (x *ZeroshotRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *ZeroshotRequest) GetPromptAudio() []byte {
	if x != nil {
		return x.PromptAudio
	}
	return nil
}

type CrosslingualRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtsText       string                 `protobuf:"bytes,1,opt,name=tts_text,json=ttsText,proto3" json:"tts_text,omitempty"`
	PromptAudio   []byte                 `protobuf:"bytes,2,opt,name=prompt_audio,json=promptAudio,proto3" json:"prompt_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrosslingualRequest) Reset() {
	*x = CrosslingualRequest{}
	mi := &file_cosyvoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrosslingualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrosslingualRequest) ProtoMessage() {}

func (x *CrosslingualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrosslingualRequest.ProtoReflect.Descriptor instead.
func (*CrosslingualRequest) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{3}
}

func (x *CrosslingualRequest) GetTtsText() string {
	if x != nil {
		return x.TtsText
	}
	return ""
}

func (x *CrosslingualRequest) GetPromptAudio() []byte {
	if x != nil {
		return x.PromptAudio
	}
	return nil
}

type InstructRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtsText       string                 `protobuf:"bytes,1,opt,name=tts_text,json=ttsText,proto3" json:"tts_text,omitempty"`
	PromptAudio   []byte                 `protobuf:"bytes,2,opt,name=prompt_audio,json=promptAudio,proto3" json:"prompt_audio,omitempty"`
	PromptText    string                 `protobuf:"bytes,3,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructRequest) Reset() {
	*x = InstructRequest{}
	mi := &file_cosyvoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructRequest) ProtoMessage() {}

func (x *InstructRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructRequest.ProtoReflect.Descriptor instead.
func (*InstructRequest) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{4}
}

func (x *InstructRequest) GetTtsText() string {
	if x != nil {
		return x.TtsText
	}
	return ""
}

func (x *InstructRequest) GetPromptAudio() []byte {
	if x != nil {
		return x.PromptAudio
	}
	return nil
}

func (x *InstructRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtsAudio      []byte                 `protobuf:"bytes,1,opt,name=tts_audio,json=ttsAudio,proto3" json:"tts_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_cosyvoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetTtsAudio() []byte {
	if x != nil {
		return x.TtsAudio
	}
	return nil
}

type ASRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRRequest) Reset() {
	*x = ASRRequest{}
	mi := &file_cosyvoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRRequest) ProtoMessage() {}

func (x *ASRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRRequest.ProtoReflect.Descriptor instead.
func (*ASRRequest) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{6}
}

func (x *ASRRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type ASRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty" dc:"如果success为false，则包含错误信息"` // 如果success为false，则包含错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRResponse) Reset() {
	*x = ASRResponse{}
	mi := &file_cosyvoice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRResponse) ProtoMessage() {}

func (x *ASRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosyvoice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRResponse.ProtoReflect.Descriptor instead.
func (*ASRResponse) Descriptor() ([]byte, []int) {
	return file_cosyvoice_proto_rawDescGZIP(), []int{7}
}

func (x *ASRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ASRResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ASRResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_cosyvoice_proto protoreflect.FileDescriptor

var file_cosyvoice_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x22, 0xbe, 0x02, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x66, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x48, 0x0a, 0x11, 0x7a, 0x65, 0x72, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x7a, 0x65, 0x72,
	0x6f, 0x53, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x15,
	0x63, 0x72, 0x6f, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x6c, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f,
	0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x6c, 0x69, 0x6e,
	0x67, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x63,
	0x72, 0x6f, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x47, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63,
	0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3e, 0x0a,
	0x0a, 0x73, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x70, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x6b,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x74, 0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x74, 0x73, 0x54, 0x65, 0x78, 0x74, 0x22, 0x70, 0x0a,
	0x0f, 0x7a, 0x65, 0x72, 0x6f, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x74, 0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x74, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22,
	0x53, 0x0a, 0x13, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x74, 0x73, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x74, 0x73, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x22, 0x70, 0x0a, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x74, 0x73, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x74, 0x73, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x27, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x74, 0x73, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x74, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22,
	0x2b, 0x0a, 0x0a, 0x41, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x0b,
	0x41, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8b,
	0x01, 0x0a, 0x09, 0x43, 0x6f, 0x73, 0x79, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09,
	0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x73, 0x79,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x44, 0x0a, 0x11, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x63, 0x6f,
	0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x73, 0x79, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x41,
	0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cosyvoice_proto_rawDescOnce sync.Once
	file_cosyvoice_proto_rawDescData []byte
)

func file_cosyvoice_proto_rawDescGZIP() []byte {
	file_cosyvoice_proto_rawDescOnce.Do(func() {
		file_cosyvoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosyvoice_proto_rawDesc), len(file_cosyvoice_proto_rawDesc)))
	})
	return file_cosyvoice_proto_rawDescData
}

var file_cosyvoice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cosyvoice_proto_goTypes = []any{
	(*Request)(nil),             // 0: cosyvoice.Request
	(*SftRequest)(nil),          // 1: cosyvoice.sftRequest
	(*ZeroshotRequest)(nil),     // 2: cosyvoice.zeroshotRequest
	(*CrosslingualRequest)(nil), // 3: cosyvoice.crosslingualRequest
	(*InstructRequest)(nil),     // 4: cosyvoice.instructRequest
	(*Response)(nil),            // 5: cosyvoice.Response
	(*ASRRequest)(nil),          // 6: cosyvoice.ASRRequest
	(*ASRResponse)(nil),         // 7: cosyvoice.ASRResponse
}
var file_cosyvoice_proto_depIdxs = []int32{
	1, // 0: cosyvoice.Request.sft_request:type_name -> cosyvoice.sftRequest
	2, // 1: cosyvoice.Request.zero_shot_request:type_name -> cosyvoice.zeroshotRequest
	3, // 2: cosyvoice.Request.cross_lingual_request:type_name -> cosyvoice.crosslingualRequest
	4, // 3: cosyvoice.Request.instruct_request:type_name -> cosyvoice.instructRequest
	0, // 4: cosyvoice.CosyVoice.Inference:input_type -> cosyvoice.Request
	6, // 5: cosyvoice.CosyVoice.SpeechRecognition:input_type -> cosyvoice.ASRRequest
	5, // 6: cosyvoice.CosyVoice.Inference:output_type -> cosyvoice.Response
	7, // 7: cosyvoice.CosyVoice.SpeechRecognition:output_type -> cosyvoice.ASRResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cosyvoice_proto_init() }
func file_cosyvoice_proto_init() {
	if File_cosyvoice_proto != nil {
		return
	}
	file_cosyvoice_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_SftRequest)(nil),
		(*Request_ZeroShotRequest)(nil),
		(*Request_CrossLingualRequest)(nil),
		(*Request_InstructRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosyvoice_proto_rawDesc), len(file_cosyvoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosyvoice_proto_goTypes,
		DependencyIndexes: file_cosyvoice_proto_depIdxs,
		MessageInfos:      file_cosyvoice_proto_msgTypes,
	}.Build()
	File_cosyvoice_proto = out.File
	file_cosyvoice_proto_goTypes = nil
	file_cosyvoice_proto_depIdxs = nil
}
